package io.dts.datasource.wrapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import io.dts.common.common.context.DtsContext;
import io.dts.datasource.DtsConnection;
import io.dts.datasource.executor.ExecutorEngine;
import io.dts.datasource.executor.SQLExecutionUnit;
import io.dts.datasource.executor.statement.StatementExecutor;
import io.dts.datasource.executor.statement.StatementUnit;
import io.dts.resourcemanager.api.IDtsConnection;

/**
 * Created by guoyubo on 2017/9/20.
 */
public class DtsStatementWrapper extends AbstractDtsStatement {

  private DtsConnection dtsConnection;

  private Statement statement;



  public DtsStatementWrapper(final DtsConnection dtsConnection, final Statement statement) {
    this.dtsConnection = dtsConnection;
    this.statement = statement;
  }

  @Override
  public ResultSet executeQuery(final String sql) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .executeQuery();
    } catch (Exception e) {
      throw new SQLException(e);
    }

  }

  private StatementUnit getStatementUnit(final String sql) throws SQLException {
    final SQLExecutionUnit sqlExecutionUnit =
        new SQLExecutionUnit(dtsConnection.getDataSource(), sql);
    return new StatementUnit(sqlExecutionUnit, this);
  }

  @Override
  public int executeUpdate(final String sql) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .executeUpdate();
    } catch (Exception e) {
      throw new SQLException(e);
    }

  }

  @Override
  public void close() throws SQLException {
    getRawStatement().close();
  }


  @Override
  public boolean execute(final String sql) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql)).execute();
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public void addBatch(final String sql) throws SQLException {
    setTargetSql(sql);
    if (DtsContext.inTxcTransaction()) {
      throw new UnsupportedOperationException("unsupport add batch in dts transaction");
    }
    getRawStatement().addBatch(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    if (DtsContext.inTxcTransaction()) {
      throw new UnsupportedOperationException("unsupport add batch in dts transaction");
    }
    getRawStatement().clearBatch();
  }

  @Override
  public int[] executeBatch() throws SQLException {
    if (DtsContext.inTxcTransaction()) {
      throw new UnsupportedOperationException("unsupport add batch in dts transaction");
    }
    return getRawStatement().executeBatch();
  }

  @Override
  public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .executeUpdate(autoGeneratedKeys);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .executeUpdate(columnIndexes);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .executeUpdate(columnNames);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .execute(autoGeneratedKeys);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .execute(columnIndexes);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public boolean execute(final String sql, final String[] columnNames) throws SQLException {
    try {
      setTargetSql(sql);
      return new StatementExecutor(ExecutorEngine.getInstance(), getStatementUnit(sql))
          .execute(columnNames);
    } catch (Exception e) {
      throw new SQLException(e);
    }
  }

  @Override
  public IDtsConnection getDtsConnection() throws SQLException {
    return dtsConnection;
  }

  @Override
  public Statement getRawStatement() throws SQLException {
    return statement;
  }


}
